---
- hosts: localhost
  connection: local
  # Variables designed for customization to match your desired deployment
  vars:
    image: ami-0a313d6098716f372
    security_groups:
      gitlab:
        description: gitlab sg
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow incoming ssh
      gitlab-server:
        description: gitlab server sg
        rules:
          - proto: tcp
            ports:
              - 80
            cidr_ip: 0.0.0.0/0
            rule_desc: allow incoming http
    instances:
      gitlab-server:
        ip: 172.16.1.1
        instance_type: t2.large
        security_groups:
          - gitlab
          - gitlab-server
        tags:
          type: gitlab-server
      gitlab-runner-shell:
        ip: 172.16.1.10
        instance_type: t2.medium
        security_groups:
          - gitlab
        tags:
          type: gitlab-runner
          role: gitlab-runner-shell
      gitlab-runner-private:
        ip: 172.16.1.11
        instance_type: t2.medium
        security_groups:
          - gitlab
        tags:
          type: gitlab-runner
          role: gitlab-runner-private
      gitlab-runner-public:
        ip: 172.16.1.12
        instance_type: t2.micro
        security_groups:
          - gitlab
        tags:
          type: gitlab-runner
          role: gitlab-runner-public

  tasks:
    - name: vpc
      ec2_vpc_net:
        name: gitlab
        cidr_block: 172.16.0.0/16
      register: gitlab_vpc

    - name: gateway
      ec2_vpc_igw:
        vpc_id: "{{ gitlab_vpc.vpc.id }}"
        state: present
      register: gitlab_igw

    - name: subnet
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ gitlab_vpc.vpc.id }}"
        cidr: 172.16.0.0/20
      register: primary_gitlab_subnet

    - name: public route
      ec2_vpc_route_table:
        vpc_id: "{{ gitlab_vpc.vpc.id }}"
        subnets:
          - 172.16.0.0/20
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ gitlab_igw.gateway_id }}"
        tags:
          Name: gitlab

    - name: security groups
      ec2_group:
        name: "{{ item.key }}"
        description: "{{ item.value.description }}"
        vpc_id: "{{ gitlab_vpc.vpc.id }}"
        rules: "{{ item.value.rules }}"
      with_dict: "{{ security_groups }}"

    - name: instances
      ec2_instance:
        name: "{{ item.key }}"
        key_name: aws
        instance_type: "{{ item.value.instance_type }}"
        image_id: "{{ image }}"
        security_groups: "{{ item.value.security_groups }}"
        vpc_subnet_id: "{{ primary_gitlab_subnet.subnet.id }}"
        wait: no
        network:
          private_ip_address: "{{ item.value.ip }}"
          assign_public_ip: yes
        tags: "{{ item.value.tags }}"
      with_dict: "{{ instances }}"
